# Required
version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

formats:
  - epub
  - pdf

python:
  version: '3.10'
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .