site_name: typing-exe

nav:
    - Home: 'index.md'
    - Quickstart: 'quickstart.md'
    - typing-exe:
        - annotations:
            - Assert: 'assert.md'
            - Modify: 'modify.md'
            - Sequence: 'sequence.md'
        - decorators:
            - execute_annotations: 'execute_annotations.md'
            - cleanup_annotations: 'cleanup_annotations.md'
        - early_return:
            - EarlyReturn: 'early_return.md'
        - parameter_data:
            - ParameterData: 'parameter_data.md'
theme: readthedocs
