site_name: typeing-exe
site_url: https://github.com/snimu/typing-exe/tree/development
repo_name: 'snimu/typing-exe'

nav:
    - Home: 'index.md'
    - Quickstart: 'quickstart.md'
    - typing-exe:
        - annotations:
            - Assert: 'Assert.md'
            - Modify: 'Modify.md'
            - Sequence: 'Sequence.md'
        - decorators:
            - execute_annotations: 'execute_annotations.md'
            - cleanup_annotations: 'cleanup_annotations.md'
        - early_return:
            - EarlyReturn: 'EarlyReturn.md'
        - parameter_data:
            - ParameterData: 'ParameterData.md'
theme: readthedocs
